version: "3.7"

services:
  influxdb:
    build: influxdb
    restart: always
    ports:
      - "8086:8086"
      - "8083:8083"
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUX_USER=admin
      - INFLUX_PASSWORD=admin
      - INFLUX_DB=influx

  grafana:
    build: grafana
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel

volumes:
  influxdb_data:
  grafana_data:
